// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Exchange.Balances.Postgres;

#nullable disable

namespace Service.Exchange.Balances.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211116000627_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("exchange_balances")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.Exchange.Balances.Postgres.Models.ExBalanceSqlEntity", b =>
                {
                    b.Property<string>("WalletIdAssetId")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ReserveBalance")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20)");

                    b.Property<string>("WalletId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("WalletIdAssetId");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId", "AssetId")
                        .IsUnique();

                    b.ToTable("balances", "exchange_balances");
                });

            modelBuilder.Entity("Service.Exchange.Balances.Postgres.Models.ProcessedOperationSqlEntity", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ProcessedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.HasKey("OperationId");

                    b.ToTable("processed_operations", "exchange_balances");
                });
#pragma warning restore 612, 618
        }
    }
}
